/*
 * Copyright (C) 2017 Spreadtrum Communications Inc.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 * updated at 2017-06-12 20:13:17
 *
 */


#ifndef ANLG_PHY_G6_H
#define ANLG_PHY_G6_H



#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_PWR_CTRL       (0x0000)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_RST_CTRL       (0x0004)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_SINE_CTRL      (0x0008)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_BB_BG_CTRL            (0x000C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANALOG_TEST           (0x0010)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_CTRL0            (0x0014)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_CTRL1            (0x0018)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_CTRL2            (0x001C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_BIST_CTRL        (0x0020)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_CTRL1            (0x0024)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_RSVD           (0x0028)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TEST_CLK_CTRL         (0x002C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TEST_SSC_CTRL         (0x0030)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_CTRL0            (0x0034)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_CTRL1            (0x0038)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_0           (0x003C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_WRAP_GLUE_CTRL        (0x0040)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_1           (0x0044)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_2           (0x0048)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_3           (0x004C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_4           (0x0050)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_CTRL2            (0x0054)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_CTRL         (0x0058)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS0         (0x005C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C0_R0    (0x0060)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C0_R1    (0x0064)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C0_R2    (0x0068)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C0_R3    (0x006C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C1_R0    (0x0070)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C1_R1    (0x0074)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C1_R2    (0x0078)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C1_R3    (0x007C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C2_R0    (0x0080)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C2_R1    (0x0084)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C2_R2    (0x0088)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C2_R3    (0x008C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C3_R0    (0x0090)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C3_R1    (0x0094)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C3_R2    (0x0098)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C3_R3    (0x009C)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_DUMY           (0x00A0)
#define REG_ANLG_PHY_G6_ANALOG_BB_TOP_REG_SEL_CFG_0         (0x00A4)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_PWR_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_REC_26MHZ_0_BUF_PD              BIT(4)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_REC_32MHZ_0_BUF_PD              BIT(3)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_BB_BG_PD                        BIT(2)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_PD                         BIT(1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_PD                         BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_RST_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_RST                        BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_SINE_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_REC_26MHZ_0_CUR_SEL(x)          (((x) & 0x3) << 19)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_REC_32MHZ_0_CUR_SEL(x)          (((x) & 0x3) << 17)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_PROBE_SEL(x)                    (((x) & 0x3F) << 11)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_SINDRV_ENA                      BIT(10)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_SINDRV_ENA_SQUARE               BIT(9)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_SINE_DRV_SEL                    BIT(8)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_CLK26M_RESERVED(x)              (((x) & 0xF) << 4)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_REC_26MHZ_SR_TRIM(x)            (((x) & 0xF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_BB_BG_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_BB_BG_RBIAS_MODE                BIT(1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_BB_CON_BG                       BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANALOG_TEST */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_ANALOG_TESTMUX(x)               (((x) & 0xFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_CTRL0 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_N(x)                       (((x) & 0x7FF) << 11)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_IBIAS(x)                   (((x) & 0x3) << 9)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_LPF(x)                     (((x) & 0x7) << 6)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_SDM_EN                     BIT(5)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_MOD_EN                     BIT(4)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_DIV_S                      BIT(3)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_REF_SEL(x)                 (((x) & 0x3) << 1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_26M_SEL                    BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_CTRL1 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_NINT(x)                    (((x) & 0x7F) << 23)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_KINT(x)                    (((x) & 0x7FFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_CTRL2 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_RESERVED(x)                (((x) & 0xFFFF) << 10)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_DIV_EN                     BIT(9)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_DIV1_EN                    BIT(8)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_BIST_EN                    BIT(7)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_26M_DIV(x)                 (((x) & 0x3F) << 1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_LOCK_DONE                  BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_BIST_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_BIST_CTRL(x)               (((x) & 0xFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_BIST_CNT(x)                (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_CTRL1 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_RESERVED(x)                (((x) & 0x3) << 20)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_G0(x)                      (((x) & 0x3) << 18)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_G1(x)                      (((x) & 0x3) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_D(x)                       (((x) & 0x3FFF) << 2)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_BPRC                       BIT(1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_OUT_SEL                    BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_RSVD */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_RESERVED(x)              (((x) & 0xFF) << 3)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_CLK26M_WCN_EN                   BIT(2)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_LVDSRFPLL_REF_SEL(x)            (((x) & 0x3))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TEST_CLK_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TEST_CLK_EN                     BIT(3)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TEST_CLK_OD                     BIT(2)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TEST_CLK_DIV(x)                 (((x) & 0x3))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TEST_SSC_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_SSC_CTRL(x)                (((x) & 0xFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_CTRL0 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_ADCLDOREF(x)            (((x) & 0x1F) << 12)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_ADCLDO_V(x)             (((x) & 0xF) << 8)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_CHOP_CLKSEL(x)          (((x) & 0x3) << 6)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_CLKSEL(x)               (((x) & 0x3) << 4)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_BIAS(x)           (((x) & 0x3) << 2)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_UGBUF_BIAS(x)           (((x) & 0x3))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_CTRL1 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_VCMI(x)           (((x) & 0x3) << 15)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_VCMO(x)           (((x) & 0x3) << 13)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_UGBUF_CTRL(x)                (((x) & 0x3) << 11)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_ADCLDO_EN               BIT(10)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_CAPCHOP_EN        BIT(9)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_CHOP_EN           BIT(8)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_UGBUF_CHOP_EN           BIT(7)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_EN                BIT(6)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_OFFSET_EN         BIT(5)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_INPUT_EN                BIT(4)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_UGBUF_EN                BIT(3)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_DATA_EDGE_SEL     BIT(2)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_SDADC_RST               BIT(1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_DOUT_TSEN_SDADC                 BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_0 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_STEP_SEL                   BIT(31)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_MAX_RANGE(x)               (((x) & 0x3FFF) << 17)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_MIN_RANGE(x)               (((x) & 0x3FFF) << 3)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_RSTN                       BIT(2)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_GEN_SEL(x)                 (((x) & 0x3))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_WRAP_GLUE_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_PD_SEL                     BIT(1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RPLL_RST_SEL                    BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_1 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_SQUA_D0(x)                 (((x) & 0x3FFF) << 14)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_SQUA_D1(x)                 (((x) & 0x3FFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_2 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_SQUA_D2(x)                 (((x) & 0x3FFF) << 14)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_SQUA_D3(x)                 (((x) & 0x3FFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_3 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_SQUA_D4(x)                 (((x) & 0x3FFF) << 14)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_SQUA_D5(x)                 (((x) & 0x3FFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_TEST_4 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_SQUA_D6(x)                 (((x) & 0x3FFF) << 14)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_AAPC_SQUA_D7(x)                 (((x) & 0x3FFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_CTRL2 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_RESERVED(x)             (((x) & 0xFF) << 5)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_BIST_EN                 BIT(4)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_BIST_CODE(x)            (((x) & 0x7) << 1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_RG_TSEN_TEST_CLK_SEL            BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_CTRL */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_CTRL_RESERVED(x)           (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_CFG3(x)           (((x) & 0x7) << 13)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_CFG2(x)           (((x) & 0x7) << 10)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_CFG1(x)           (((x) & 0x7) << 7)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_CFG0(x)           (((x) & 0x7) << 4)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_CODE(x)           (((x) & 0x7) << 1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_EN                BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS0 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_STS0_RESERVED(x)           (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_STS0_RESERVED1(x)          (((x) & 0x1F) << 11)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_CODE_SEL          BIT(10)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_TIME_SEL_CFG3(x)  (((x) & 0x3) << 8)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_TIME_SEL_CFG2(x)  (((x) & 0x3) << 6)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_TIME_SEL_CFG1(x)  (((x) & 0x3) << 4)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_TIME_SEL_CFG0(x)  (((x) & 0x3) << 2)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_BYPASS            BIT(1)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_BIST_DONE              BIT(0)

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C0_R0 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_STS0_C0_R0_RESERVED(x)     (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C0_RES0(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C0_R1 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C0_R1_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C0_RES1(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C0_R2 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C0_R2_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C0_RES2(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C0_R3 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C0_R3_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C0_RES3(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C1_R0 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C1_R0_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C1_RES0(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C1_R1 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C1_R1_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C1_RES1(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C1_R2 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C1_R2_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C1_RES2(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C1_R3 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C1_R3_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C1_RES3(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C2_R0 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C2_R0_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C2_RES0(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C2_R1 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C2_R1_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C2_RES1(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C2_R2 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C2_R2_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C2_RES2(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C2_R3 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C2_R3_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C2_RES3(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C3_R0 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C3_R0_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C3_RES0(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C3_R1 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C3_R1_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C3_RES1(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C3_R2 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C3_R2_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C3_RES2(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_STS_C3_R3 */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TSEN_C3_R3_RESERVED(x)          (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_TST_TSEN_C3_RES3(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_ANA_BB_DUMY */

#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_ANALOG_BB_DUMY_IN(x)            (((x) & 0xFFFF) << 16)
#define BIT_ANLG_PHY_G6_ANALOG_BB_TOP_ANALOG_BB_DUMY_OUT(x)           (((x) & 0xFFFF))

/* REG_ANLG_PHY_G6_ANALOG_BB_TOP_REG_SEL_CFG_0 */

#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_REC_26MHZ_0_BUF_PD      BIT(29)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_REC_32MHZ_0_BUF_PD      BIT(28)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_PD                 BIT(27)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_AAPC_PD                 BIT(26)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_RST                BIT(25)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_SINDRV_ENA              BIT(24)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_SINDRV_ENA_SQUARE       BIT(23)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_N                  BIT(22)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_IBIAS              BIT(21)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_LPF                BIT(20)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_SDM_EN             BIT(19)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_MOD_EN             BIT(18)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_DIV_S              BIT(17)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_REF_SEL            BIT(16)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_NINT               BIT(15)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_KINT               BIT(14)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_RESERVED           BIT(13)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_BIST_EN            BIT(12)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_26M_DIV            BIT(11)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RPLL_BIST_CTRL          BIT(10)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_AAPC_RESERVED           BIT(9)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_AAPC_G0                 BIT(8)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_AAPC_G1                 BIT(7)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_AAPC_D                  BIT(6)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_AAPC_OUT_SEL            BIT(5)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RG_TSEN_SDADC_RST       BIT(4)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RG_TSEN_RESERVED        BIT(3)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RG_TSEN_BIST_EN         BIT(2)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RG_TSEN_BIST_CODE       BIT(1)
#define BIT_ANLG_PHY_G6_DBG_SEL_ANALOG_BB_TOP_RG_TSEN_TEST_CLK_SEL    BIT(0)


#endif /* ANLG_PHY_G6_H */

