#
# sprd_fd.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#
KO_MODULE_NAME := sprd_fd
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

FD_DIR := $(BSP_BOARD_CAMERA_MODULE_FD_VERSION)
KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/$(FD_DIR)/*.c)

#
# Build Options
#
ccflags-y += -I$(KO_MODULE_PATH)/../core/isp2.6/adpt/sharkl5pro/inc
ccflags-y += -I$(KO_MODULE_PATH)/../core/isp2.6/inc/
ccflags-y += -I$(KO_MODULE_PATH)/../common
ccflags-y += -I$(KO_MODULE_PATH)/../interface
ccflags-y += -I$(srctree)/drivers/staging/android/ion

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
