# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_ICNT_FINGERPRINT)	+= fpsensor_tee/
obj-$(CONFIG_EGIS_FINGERPRINT)	+= egis/
obj-$(CONFIG_SILEAD_FINGERPRINT)	+= silead/
obj-$(CONFIG_FOCAL_FINGERPRINT)	+= focaltech/
