/*
 * Copyright (C) 2012-2017 Spreadtrum Communications Inc.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _ISP_R6P91_REG_H_
#define _ISP_R6P91_REG_H_

extern unsigned long s_isp_regbase;
#define ISP_BASE (s_isp_regbase)
#define ISP_BASE_ADDR                      ISP_BASE

/*isp sub block: Interrupt*/
#define ISP_INT_STATUS                     (0x0000UL)
#define ISP_INT_EN0                        (0x0014UL)
#define ISP_INT_CLR0                       (0x0018UL)
#define ISP_INT_RAW0                       (0x001CUL)
#define ISP_INT_INT0                       (0x0020UL)
#define ISP_INT_EN1                        (0x0024UL)
#define ISP_INT_CLR1                       (0x0028UL)
#define ISP_INT_RAW1                       (0x002CUL)
#define ISP_INT_INT1                       (0x0030UL)
#define ISP_INT_EN2                        (0x0034UL)
#define ISP_INT_CLR2                       (0x0038UL)
#define ISP_INT_RAW2                       (0x003CUL)
#define ISP_INT_INT2                       (0x0040UL)
#define ISP_INT_EN3                        (0x0044UL)
#define ISP_INT_CLR3                       (0x0048UL)
#define ISP_INT_RAW3                       (0x004CUL)
#define ISP_INT_INT3                       (0x0050UL)
#define ISP_INT_ALL_DONE_CTRL              (0x0054UL)

/*isp sub block: Fetch*/
#define ISP_FETCH_MEM_STATUS0              (0x0100UL)
#define ISP_FETCH_MEM_STATUS1              (0x0104UL)
#define ISP_FETCH_DCAM_STATUS0             (0x0108UL)
#define ISP_FETCH_MIPI_STATUS              (0x010CUL)
#define ISP_FETCH_PARAM                    (0x0114UL)
#define ISP_FETCH_START                    (0x0118UL)
#define ISP_FETCH_SLICE_SIZE               (0x0120UL)
#define ISP_FETCH_SLICE_Y_ADDR             (0x0124UL)
#define ISP_FETCH_SLICE_Y_PITCH            (0x0128UL)
#define ISP_FETCH_SLICE_U_ADDR             (0x012CUL)
#define ISP_FETCH_SLICE_U_PITCH            (0x0130UL)
#define ISP_FETCH_SLICE_V_ADDR             (0x0134UL)
#define ISP_FETCH_SLICE_V_PITCH            (0x0138UL)
#define ISP_FETCH_MIPI_WORD_INFO           (0x013CUL)
#define ISP_FETCH_MIPI_BYTE_INFO           (0x0140UL)
#define ISP_FETCH_LINE_DLY_CTRL            (0x0144UL)

/*isp sub block: Store*/
#define ISP_STORE_STATUS_MEM0              (0x0200UL)
#define ISP_STORE_STATUS_MEM1              (0x0204UL)
#define ISP_STORE_STATUS_DCAM0             (0x0208UL)
#define ISP_STORE_STATUS_DCAM1             (0x020CUL)
#define ISP_STORE_PARAM                    (0x0214UL)
#define ISP_STORE_SLICE_SIZE               (0x0218UL)
#define ISP_STORE_BORDER                   (0x021CUL)
#define ISP_STORE_Y_ADDR                   (0x0220UL)
#define ISP_STORE_Y_PITCH                  (0x0224UL)
#define ISP_STORE_U_ADDR                   (0x0228UL)
#define ISP_STORE_U_PITCH                  (0x022CUL)
#define ISP_STORE_V_ADDR                   (0x0230UL)
#define ISP_STORE_V_PITCH                  (0x0234UL)
#define ISP_STORE_SHADOW_CLR               (0x0238UL)
#define ISP_STORE_READ_CTL                 (0x023CUL)

/*isp sub block: dispatch*/
#define ISP_DISPATCH_STATUS_CH0            (0x0300UL)
#define ISP_DISPATCH_STATUS_CH1            (0x0304UL)
#define ISP_DISPATCH_STATUS_COMM           (0x0308UL)
#define ISP_DISPATCH_STATUS1_CH0           (0x030CUL)
#define ISP_DISPATCH_STATUS1_CH1           (0x0310UL)
#define ISP_DISPATCH_CH0_BAYER             (0x0314UL)
#define ISP_DISPATCH_CH0_SIZE              (0x0318UL)
#define ISP_DISPATCH_CH1_SIZE              (0x031CUL)
#define ISP_DISPATCH_DLY                   (0x0320UL)
#define ISP_DISPATCH_CH1_BAYER             (0x0324UL)
#define ISP_DISPATCH_HW_CTRL_CH0           (0x0328UL)
#define ISP_DISPATCH_HW_CTRL_CH1           (0x032CUL)
#define ISP_DISPATCH_STATUS_DBG_CH0        (0x0350UL)
#define ISP_DISPATCH_STATUS_DBG_CH1        (0x0354UL)

/*isp sub block: arbiter*/
#define ISP_ARBITER_WR_STATUS              (0x0400UL)
#define ISP_ARBITER_RD_STATUS              (0x0404UL)
#define ISP_ARBITER_PARAM                  (0x0414UL)
#define ISP_ARBITER_ENDIAN_CH0             (0x0418UL)
#define ISP_ARBITER_ENDIAN_CH1             (0x041CUL)
#define ISP_ARBITER_CTRL                   (0x0420UL)

/*isp sub block: axi*/
#define ISP_AXI_WR_MASTER_STATUS           (0x0500UL)
#define ISP_AXI_RD_MASTER_STATUS           (0x0504UL)
#define ISP_AXI_ITI2AXIM_CTRL              (0x0514UL)
#define ISP_AXI_CONVERT_WR_CTRL            (0x0518UL)
#define ISP_AXI_ISOLATION                  (0x051CUL)
#define ISP_AXI_STATUS0                    (0x0520UL)
#define ISP_AXI_STATUS1                    (0x0524UL)
#define ISP_AXI_STATUS2                    (0x0528UL)
#define ISP_AXI_STATUS3                    (0x052CUL)

/*isp sub block: common*/
#define ISP_COMMON_VERSION                 (0x0700UL)
#define ISP_COMMON_STATUS0                 (0x0704UL)
#define ISP_COMMON_STATUS1                 (0x0708UL)
#define ISP_COMMON_CTRL_CH0                (0x0714UL)
#define ISP_COMMON_SPACE_SEL               (0x0718UL)
#define ISP_COMMON_CTRL_AWBM               (0x0720UL)
#define ISP_COMMON_PMU_RAW_MASK            (0x0724UL)
#define ISP_COMMON_PMU_HW_MASK             (0x0728UL)
#define ISP_COMMON_PMU_HW_ENABLE           (0x072CUL)
#define ISP_COMMON_PMU_SW_SWITCH           (0x0730UL)
#define ISP_COMMON_PMU_SW_TOGGLE           (0x0734UL)
#define ISP_COMMON_LBUF_OFFSET0            (0x0738UL)
#define ISP_SHADOW_CTRL_CH0                (0x073CUL)
#define ISP_COMMON_3A_CTRL0                (0x0744UL)
#define ISP_COMMON_LBUF_OFFSET1            (0x0748UL)
#define ISP_COMMON_RESERVED0               (0x0750UL)
#define ISP_COMMON_RESERVED1               (0x0754UL)
#define ISP_COMMON_RESERVED2               (0x0758UL)
#define ISP_GCLK_CTRL0                     (0x0760UL)
#define ISP_GCLK_CTRL1                     (0x0764UL)
#define ISP_GCLK_CTRL2                     (0x0768UL)

/*isp sub block: ap_mmu_isp_sw_rf, need to add more regs*/
#define ISP_MMU_INT_EN                     (0x0800UL)
#define ISP_MMU_INT_CLR                    (0x0804UL)
#define ISP_MMU_INT_RAW_STS                (0x0808UL)
#define ISP_MMU_INT_MASKED_STS             (0x080CUL)
#define ISP_MMU_W_BYPASS                   (0x0810UL)
#define ISP_MMU_R_BYPASS                   (0x0814UL)
#define ISP_MMU_W_TLB_EN                   (0x0818UL)
#define ISP_MMU_R_TLB_EB                   (0x081CUL)
#define ISP_MMU_CFG                        (0x0820UL)
#define ISP_MMU_FIRST_VPN                  (0x0824UL)
#define ISP_MMU_PTBA_LO                    (0x0828UL)
#define ISP_MMU_PTBA_HI                    (0x082CUL)
#define ISP_MMU_PT_SIZE                    (0x0830UL)
#define ISP_MMU_DEFAULT_PPN                (0x0834UL)
#define ISP_MMU_REV                                (0x09FCUL)

/*isp sub block: Pre Global Gain*/
#define ISP_PGG_STATUS                     (0x1000UL)
#define ISP_PGG_PARAM                      (0x1014UL)

/*isp sub block: BLC: back level calibration*/
#define ISP_BLC_STATUS                     (0x1100UL)
#define ISP_BLC_PARAM                      (0x1114UL)
#define ISP_BLC_B_PARAM_R_B                (0x1118UL)
#define ISP_BLC_B_PARAM_G                  (0x111CUL)

/*isp sub block: RGBG*/
#define ISP_RGBG_STATUS                    (0x1200UL)
#define ISP_RGBG_PARAM                     (0x1214UL)
#define ISP_RGBG_RB                        (0x1218UL)
#define ISP_RGBG_G                         (0x121CUL)

/*isp sub block: lens shading calibration*/
#define ISP_LENS_STATUS                    (0x1500UL)
#define ISP_LENS_PARAM                     (0x1514UL)
#define ISP_LENS_PARAM_ADDR                (0x1518UL)
#define ISP_LENS_SLICE_POS                 (0x151CUL)
#define ISP_LENS_LOAD_EB                   (0x1520UL)
#define ISP_LENS_GRID_PITCH                (0x1524UL)
#define ISP_LENS_GRID_SIZE                 (0x1528UL)
#define ISP_LENS_LOAD_BUF                  (0x152CUL)
#define ISP_LENS_MISC                      (0x1530UL)
#define ISP_LENS_SLICE_SIZE                (0x1534UL)
#define ISP_LENS_INIT_COOR                 (0x1538UL)
#define ISP_LENS_Q0_VALUE                  (0x153CUL)
#define ISP_LENS_Q1_VALUE                  (0x1540UL)
#define ISP_LENS_Q2_VALUE                  (0x1544UL)
#define ISP_LENS_Q3_VALUE                  (0x1548UL)
#define ISP_LENS_Q4_VALUE                  (0x154CUL)

/*isp sub block: binning*/
#define ISP_BINNING_STATUS                 (0x1600UL)
#define ISP_BINNING_PARAM                  (0x1614UL)
#define ISP_BINNING_MEM_ADDR               (0x1618UL)
#define ISP_BINNING_PITCH                  (0x161CUL)

/*isp sub block: AWBC*/
#define ISP_AWBC_STATUS                    (0x1800UL)
#define ISP_AWBC_PARAM                     (0x1814UL)
#define ISP_AWBC_GAIN0                     (0x1818UL)
#define ISP_AWBC_GAIN1                     (0x181CUL)
#define ISP_AWBC_THRD                      (0x1820UL)
#define ISP_AWBC_OFFSET0                   (0x1824UL)
#define ISP_AWBC_OFFSET1                   (0x1828UL)

/*isp sub block: AEM*/
#define ISP_AEM_STATUS                     (0x1900UL)
#define ISP_AEM_PARAM                      (0x1914UL)
#define ISP_AEM_OFFSET                     (0x1918UL)
#define ISP_AEM_BLK_SIZE                   (0x191CUL)
#define ISP_AEM_SLICE_SIZE                 (0x1920UL)
#define ISP_AEM_SLICE_INIT_ADDR            (0x1924UL)
#define ISP_AEM_SLICE_DDR_PARAM            (0x1928UL)

/*isp sub block: BPC: bad pixel correction*/
#define ISP_BPC_STATUS                     (0x1A00UL)
#define ISP_BPC_PARAM                      (0x1A14UL)
#define ISP_BPC_CFG                        (0x1A18UL)
#define ISP_BPC_FACTOR                     (0x1A1CUL)
#define ISP_BPC_COEFF                      (0x1A20UL)
#define ISP_BPC_LUTWORD0                   (0x1A24UL)
#define ISP_BPC_LUTWORD1                   (0x1A28UL)
#define ISP_BPC_LUTWORD2                   (0x1A2CUL)
#define ISP_BPC_LUTWORD3                   (0x1A30UL)
#define ISP_BPC_LUTWORD4                   (0x1A34UL)
#define ISP_BPC_LUTWORD5                   (0x1A38UL)
#define ISP_BPC_LUTWORD6                   (0x1A3CUL)
#define ISP_BPC_LUTWORD7                   (0x1A40UL)
#define ISP_BPC_NEW_OLD_SEL                (0x1A44UL)
#define ISP_BPC_MAP_ADDR                   (0x1A48UL)

/*isp sub block: GRGB*/
#define ISP_GRGB_STATUS                    (0x1B00UL)
#define ISP_GRGB_PARAM                     (0x1B14UL)
#define ISP_GRGB_GRID                      (0x1B18UL)

/*isp sub block: BDN*/
#define ISP_BDN_STATUS                     (0x1C00UL)
#define ISP_BDN_STATUS1                    (0x1C04UL)
#define ISP_BDN_PARAM                      (0x1C14UL)
#define ISP_BDN_DISWEI0_0                  (0x1C18UL)
#define ISP_BDN_DISWEI0_1                  (0x1C1CUL)
#define ISP_BDN_RANWEI0_0                  (0x1C20UL)
#define ISP_BDN_RANWEI0_1                  (0x1C24UL)
#define ISP_BDN_RANWEI0_2                  (0x1C28UL)
#define ISP_BDN_RANWEI0_3                  (0x1C2CUL)
#define ISP_BDN_RANWEI0_4                  (0x1C30UL)
#define ISP_BDN_RANWEI0_5                  (0x1C34UL)
#define ISP_BDN_RANWEI0_6                  (0x1C38UL)
#define ISP_BDN_RANWEI0_7                  (0x1C3CUL)
#define ISP_BDN_DISWEI1_0                  (0x1C40UL)
#define ISP_BDN_DISWEI1_1                  (0x1C44UL)
#define ISP_BDN_RANWEI1_0                  (0x1C48UL)
#define ISP_BDN_RANWEI1_1                  (0x1C4CUL)
#define ISP_BDN_RANWEI1_2                  (0x1C50UL)
#define ISP_BDN_RANWEI1_3                  (0x1C54UL)
#define ISP_BDN_RANWEI1_4                  (0x1C58UL)
#define ISP_BDN_RANWEI1_5                  (0x1C5CUL)
#define ISP_BDN_RANWEI1_6                  (0x1C60UL)
#define ISP_BDN_RANWEI1_7                  (0x1C64UL)
#define ISP_BDN_DISWEI2_0                  (0x1C68UL)
#define ISP_BDN_DISWEI2_1                  (0x1C6CUL)
#define ISP_BDN_RANWEI2_0                  (0x1C70UL)
#define ISP_BDN_RANWEI2_1                  (0x1C74UL)
#define ISP_BDN_RANWEI2_2                  (0x1C78UL)
#define ISP_BDN_RANWEI2_3                  (0x1C7CUL)
#define ISP_BDN_RANWEI2_4                  (0x1C80UL)
#define ISP_BDN_RANWEI2_5                  (0x1C84UL)
#define ISP_BDN_RANWEI2_6                  (0x1C88UL)
#define ISP_BDN_RANWEI2_7                  (0x1C8CUL)
#define ISP_BDN_DISWEI3_0                  (0x1C90UL)
#define ISP_BDN_DISWEI3_1                  (0x1C94UL)
#define ISP_BDN_RANWEI3_0                  (0x1C98UL)
#define ISP_BDN_RANWEI3_1                  (0x1C9CUL)
#define ISP_BDN_RANWEI3_2                  (0x1CA0UL)
#define ISP_BDN_RANWEI3_3                  (0x1CA4UL)
#define ISP_BDN_RANWEI3_4                  (0x1CA8UL)
#define ISP_BDN_RANWEI3_5                  (0x1CACUL)
#define ISP_BDN_RANWEI3_6                  (0x1CB0UL)
#define ISP_BDN_RANWEI3_7                  (0x1CB4UL)
#define ISP_BDN_DISWEI4_0                  (0x1CB8UL)
#define ISP_BDN_DISWEI4_1                  (0x1CBCUL)
#define ISP_BDN_RANWEI4_0                  (0x1CC0UL)
#define ISP_BDN_RANWEI4_1                  (0x1CC4UL)
#define ISP_BDN_RANWEI4_2                  (0x1CC8UL)
#define ISP_BDN_RANWEI4_3                  (0x1CCCUL)
#define ISP_BDN_RANWEI4_4                  (0x1CD0UL)
#define ISP_BDN_RANWEI4_5                  (0x1CD4UL)
#define ISP_BDN_RANWEI4_6                  (0x1CD8UL)
#define ISP_BDN_RANWEI4_7                  (0x1CDCUL)
#define ISP_BDN_DISWEI5_0                  (0x1CE0UL)
#define ISP_BDN_DISWEI5_1                  (0x1CE4UL)
#define ISP_BDN_RANWEI5_0                  (0x1CE8UL)
#define ISP_BDN_RANWEI5_1                  (0x1CECUL)
#define ISP_BDN_RANWEI5_2                  (0x1CF0UL)
#define ISP_BDN_RANWEI5_3                  (0x1CF4UL)
#define ISP_BDN_RANWEI5_4                  (0x1CF8UL)
#define ISP_BDN_RANWEI5_5                  (0x1CFCUL)
#define ISP_BDN_RANWEI5_6                  (0x1D00UL)
#define ISP_BDN_RANWEI5_7                  (0x1D04UL)
#define ISP_BDN_DISWEI6_0                  (0x1D08UL)
#define ISP_BDN_DISWEI6_1                  (0x1D0CUL)
#define ISP_BDN_RANWEI6_0                  (0x1D10UL)
#define ISP_BDN_RANWEI6_1                  (0x1D14UL)
#define ISP_BDN_RANWEI6_2                  (0x1D18UL)
#define ISP_BDN_RANWEI6_3                  (0x1D1CUL)
#define ISP_BDN_RANWEI6_4                  (0x1D20UL)
#define ISP_BDN_RANWEI6_5                  (0x1D24UL)
#define ISP_BDN_RANWEI6_6                  (0x1D28UL)
#define ISP_BDN_RANWEI6_7                  (0x1D2CUL)
#define ISP_BDN_DISWEI7_0                  (0x1D30UL)
#define ISP_BDN_DISWEI7_1                  (0x1D34UL)
#define ISP_BDN_RANWEI7_0                  (0x1D38UL)
#define ISP_BDN_RANWEI7_1                  (0x1D3CUL)
#define ISP_BDN_RANWEI7_2                  (0x1D40UL)
#define ISP_BDN_RANWEI7_3                  (0x1D44UL)
#define ISP_BDN_RANWEI7_4                  (0x1D48UL)
#define ISP_BDN_RANWEI7_5                  (0x1D4CUL)
#define ISP_BDN_RANWEI7_6                  (0x1D50UL)
#define ISP_BDN_RANWEI7_7                  (0x1D54UL)
#define ISP_BDN_DISWEI8_0                  (0x1D58UL)
#define ISP_BDN_DISWEI8_1                  (0x1D5CUL)
#define ISP_BDN_RANWEI8_0                  (0x1D60UL)
#define ISP_BDN_RANWEI8_1                  (0x1D64UL)
#define ISP_BDN_RANWEI8_2                  (0x1D68UL)
#define ISP_BDN_RANWEI8_3                  (0x1D6CUL)
#define ISP_BDN_RANWEI8_4                  (0x1D70UL)
#define ISP_BDN_RANWEI8_5                  (0x1D74UL)
#define ISP_BDN_RANWEI8_6                  (0x1D78UL)
#define ISP_BDN_RANWEI8_7                  (0x1D7CUL)
#define ISP_BDN_DISWEI9_0                  (0x1D80UL)
#define ISP_BDN_DISWEI9_1                  (0x1D84UL)
#define ISP_BDN_RANWEI9_0                  (0x1D88UL)
#define ISP_BDN_RANWEI9_1                  (0x1D8CUL)
#define ISP_BDN_RANWEI9_2                  (0x1D90UL)
#define ISP_BDN_RANWEI9_3                  (0x1D94UL)
#define ISP_BDN_RANWEI9_4                  (0x1D98UL)
#define ISP_BDN_RANWEI9_5                  (0x1D9CUL)
#define ISP_BDN_RANWEI9_6                  (0x1DA0UL)
#define ISP_BDN_RANWEI9_7                  (0x1DA4UL)
#define ISP_BDN_1DLNC_CENTER               (0x1DA8UL)
#define ISP_BDN_1DLNC_SQUARE_X             (0x1DACUL)
#define ISP_BDN_1DLNC_SQUARE_Y             (0x1DB0UL)
#define ISP_BDN_1DLNC_P                    (0x1DB4UL)
#define ISP_BDN_1DLNC_SIZE                 (0x1DB8UL)
#define ISP_BDN_1DLNC_POS                  (0x1DBCUL)
#define	ISP_BDN_1DLNC_OFFSET               (0x1DC0UL)

/*isp sub block: VST*/
#define ISP_VST_PARA                       (0x2014UL)

/*isp sub block: NLM*/
#define ISP_NLM_LB_STATUS0                 (0x2100UL)
#define ISP_NLM_LB_STATUS1                 (0x2104UL)
#define ISP_NLM_STATUS                     (0x2108UL)
#define ISP_NLM_PARA                       (0x2114UL)
#define ISP_NLM_FLAT_PARA_0                (0x2118UL)
#define ISP_NLM_FLAT_PARA_1                (0x211CUL)
#define ISP_NLM_FLAT_PARA_2                (0x2120UL)
#define ISP_NLM_FLAT_PARA_3                (0x2124UL)
#define ISP_NLM_FLAT_PARA_4                (0x2128UL)
#define ISP_NLM_STERNGTH                   (0x212CUL)
#define ISP_NLM_IS_FLAT                    (0x2130UL)
#define ISP_NLM_ADD_BACK                   (0x2134UL)
#define ISP_NLM_DIRECTION_0                (0x2138UL)
#define ISP_NLM_DIRECTION_1                (0x213CUL)
#define ISP_NLM_LUT_W_0                    (0x2140UL)
#define ISP_NLM_LUT_W_1                    (0x2144UL)
#define ISP_NLM_LUT_W_2                    (0x2148UL)
#define ISP_NLM_LUT_W_3                    (0x214CUL)
#define ISP_NLM_LUT_W_4                    (0x2150UL)
#define ISP_NLM_LUT_W_5                    (0x2154UL)
#define ISP_NLM_LUT_W_6                    (0x2158UL)
#define ISP_NLM_LUT_W_7                    (0x215CUL)
#define ISP_NLM_LUT_W_8                    (0x2160UL)
#define ISP_NLM_LUT_W_9                    (0x2164UL)
#define ISP_NLM_LUT_W_10                   (0x2168UL)
#define ISP_NLM_LUT_W_11                   (0x216CUL)
#define ISP_NLM_LUT_W_12                   (0x2170UL)
#define ISP_NLM_LUT_W_13                   (0x2174UL)
#define ISP_NLM_LUT_W_14                   (0x2178UL)
#define ISP_NLM_LUT_W_15                   (0x217CUL)
#define ISP_NLM_LUT_W_16                   (0x2180UL)
#define ISP_NLM_LUT_W_17                   (0x2184UL)
#define ISP_NLM_LUT_W_18                   (0x2188UL)
#define ISP_NLM_LUT_W_19                   (0x218CUL)
#define ISP_NLM_LUT_W_20                   (0x2190UL)
#define ISP_NLM_LUT_W_21                   (0x2194UL)
#define ISP_NLM_LUT_W_22                   (0x2198UL)
#define ISP_NLM_LUT_W_23                   (0x219CUL)
#define ISP_NLM_ADD_BACK_NEW0              (0x21A0UL)
#define ISP_NLM_ADD_BACK_NEW1              (0x21A4UL)

/*isp sub block: IVST*/
#define ISP_IVST_PARA                      (0x2214UL)

/*isp sub block: CFA: clolor filter array*/
#define ISP_CFAE_STATUS                    (0x3000UL)
#define ISP_CFAE_EE_CFG0                   (0x3014UL)
#define ISP_CFAE_THRD_0                    (0x3018UL)
#define ISP_CFAE_THRD_1                    (0x301CUL)
#define ISP_CFAE_THRD_2                    (0x3020UL)
#define ISP_CFAE_THRD_3                    (0x3024UL)
#define ISP_CFAE_THRD_4                    (0x3028UL)
#define ISP_CFAE_EE_CFG1                   (0x302CUL)

/*isp sub block:CMC: Color matrix correction for 10 bit   */
#define ISP_CMC10_STATUS0                  (0x3100UL)
#define ISP_CMC10_STATUS1                  (0x3104UL)
#define ISP_CMC10_PARAM                    (0x3114UL)
#define ISP_CMC10_MATRIX0                  (0x3118UL)
#define ISP_CMC10_MATRIX1                  (0x311CUL)
#define ISP_CMC10_MATRIX2                  (0x3120UL)
#define ISP_CMC10_MATRIX3                  (0x3124UL)
#define ISP_CMC10_MATRIX4                  (0x3128UL)

/*isp sub block: GAMMA */
#define ISP_GAMMA_STATUS                   (0x3300UL)
#define ISP_GAMMA_PARAM                    (0x3314UL)

/*isp sub block: CCE: clolor conversion enhancement*/
#define ISP_CCE_STATUS0                    (0x3700UL)
#define ISP_CCE_STATUS1                    (0x3704UL)
#define ISP_CCE_PARAM                      (0x3714UL)
#define ISP_CCE_MATRIX0                    (0x3718UL)
#define ISP_CCE_MATRIX1                    (0x371CUL)
#define ISP_CCE_MATRIX2                    (0x3720UL)
#define ISP_CCE_MATRIX3                    (0x3724UL)
#define ISP_CCE_MATRIX4                    (0x3728UL)
#define ISP_CCE_SHIFT                      (0x372CUL)
#define ISP_CCE_UVD_PARAM0                 (0x3730UL)
#define ISP_CCE_UVD_PARAM1                 (0x3734UL)
#define ISP_CCE_UVD_PARAM2                 (0x3738UL)
#define ISP_CCE_UVD_PARAM3                 (0x373CUL)
#define ISP_CCE_UVD_PARAM4                 (0x3740UL)
#define ISP_CCE_UVD_PARAM5                 (0x3744UL)

/*isp sub block:HSV*/
#define ISP_HSV_STATUS                     (0x3800UL)
#define ISP_HSV_PARAM                      (0x3814UL)

/*isp sub block:ISP_PRECNRNEW*/
#define ISP_PRECNRNEW_STATUS0              (0x3A00UL)
#define ISP_PRECNRNEW_STATUS1              (0x3A04UL)
#define ISP_PRECNRNEW_CFG                  (0x3A14UL)
#define ISP_PRECNRNEW_MEDIAN_THR           (0x3A18UL)
#define ISP_PRECNRNEW_THRU                 (0x3A1CUL)
#define ISP_PRECNRNEW_THRV                 (0x3A20UL)

/*isp sub block:ISP_PSTRZ*/
#define ISP_PSTRZ_STATUS                   (0x3B00UL)
#define ISP_PSTRZ_PARAM                    (0x3B14UL)
#define ISP_PSTRZ_LEVEL0                   (0x3B18UL)
#define ISP_PSTRZ_LEVEL1                   (0x3B1CUL)
#define ISP_PSTRZ_LEVEL2                   (0x3B20UL)
#define ISP_PSTRZ_LEVEL3                   (0x3B24UL)
#define ISP_PSTRZ_LEVEL4                   (0x3B28UL)
#define ISP_PSTRZ_LEVEL5                   (0x3B2CUL)
#define ISP_PSTRZ_LEVEL6                   (0x3B30UL)
#define ISP_PSTRZ_LEVEL7                   (0x3B34UL)

/*isp sub block: AFM : auto focus monitor*/
#define ISP_RGB_AFM_STATUS0                  (0x3C00UL)
#define ISP_RGB_AFM_STATUS1                  (0x3C04UL)
#define ISP_RGB_AFM_PARAM                    (0x3C14UL)
#define ISP_RGB_AFM_FRAME_RANGE              (0x3C18UL)
#define ISP_RGB_AFM_SOBEL5_THR_R           (0x3C1CUL)
#define ISP_RGB_AFM_SOBEL9_THR_R           (0x3C20UL)
#define ISP_RGB_AFM_SPSMD_THR_R            (0x3C24UL)
#define ISP_RGB_AFM_WIN_RANGE0S              (0x3C28UL)
#define ISP_RGB_AFM_WIN_RANGE0E              (0x3C2CUL)
#define ISP_RGB_AFM_WIN_RANGE1S              (0x3C30UL)
#define ISP_RGB_AFM_WIN_RANGE1E              (0x3C34UL)
#define ISP_RGB_AFM_WIN_RANGE2S              (0x3C38UL)
#define ISP_RGB_AFM_WIN_RANGE2E              (0x3C3CUL)
#define ISP_RGB_AFM_WIN_RANGE3S              (0x3C40UL)
#define ISP_RGB_AFM_WIN_RANGE3E              (0x3C44UL)
#define ISP_RGB_AFM_WIN_RANGE4S              (0x3C48UL)
#define ISP_RGB_AFM_WIN_RANGE4E              (0x3C4CUL)
#define ISP_RGB_AFM_WIN_RANGE5S              (0x3C50UL)
#define ISP_RGB_AFM_WIN_RANGE5E              (0x3C54UL)
#define ISP_RGB_AFM_WIN_RANGE6S              (0x3C58UL)
#define ISP_RGB_AFM_WIN_RANGE6E              (0x3C5CUL)
#define ISP_RGB_AFM_WIN_RANGE7S              (0x3C60UL)
#define ISP_RGB_AFM_WIN_RANGE7E              (0x3C64UL)
#define ISP_RGB_AFM_WIN_RANGE8S              (0x3C68UL)
#define ISP_RGB_AFM_WIN_RANGE8E              (0x3C6CUL)
#define ISP_RGB_AFM_WIN_RANGE9S              (0x3C70UL)
#define ISP_RGB_AFM_WIN_RANGE9E              (0x3C74UL)
#define ISP_RGB_AFM_ROI_0_SOBEL5X5_R_0       (0x3C78UL)
#define ISP_RGB_AFM_ROI_0_SOBEL5X5_G_0       (0x3C7CUL)
#define ISP_RGB_AFM_ROI_0_SOBEL5X5_B_0       (0x3C80UL)
#define ISP_RGB_AFM_ROI_1_SOBEL5X5_R_0       (0x3C84UL)
#define ISP_RGB_AFM_ROI_1_SOBEL5X5_G_0       (0x3C88UL)
#define ISP_RGB_AFM_ROI_1_SOBEL5X5_B_0       (0x3C8CUL)
#define ISP_RGB_AFM_ROI_2_SOBEL5X5_R_0       (0x3C90UL)
#define ISP_RGB_AFM_ROI_2_SOBEL5X5_G_0       (0x3C94UL)
#define ISP_RGB_AFM_ROI_2_SOBEL5X5_B_0       (0x3C98UL)
#define ISP_RGB_AFM_ROI_3_SOBEL5X5_R_0       (0x3C9CUL)
#define ISP_RGB_AFM_ROI_3_SOBEL5X5_G_0       (0x3CA0UL)
#define ISP_RGB_AFM_ROI_3_SOBEL5X5_B_0       (0x3CA4UL)
#define ISP_RGB_AFM_ROI_4_SOBEL5X5_R_0       (0x3CA8UL)
#define ISP_RGB_AFM_ROI_4_SOBEL5X5_G_0       (0x3CACUL)
#define ISP_RGB_AFM_ROI_4_SOBEL5X5_B_0       (0x3CB0UL)
#define ISP_RGB_AFM_ROI_5_SOBEL5X5_R_0       (0x3CB4UL)
#define ISP_RGB_AFM_ROI_5_SOBEL5X5_G_0       (0x3CB8UL)
#define ISP_RGB_AFM_ROI_5_SOBEL5X5_B_0       (0x3CBCUL)
#define ISP_RGB_AFM_ROI_6_SOBEL5X5_R_0       (0x3CC0UL)
#define ISP_RGB_AFM_ROI_6_SOBEL5X5_G_0       (0x3CC4UL)
#define ISP_RGB_AFM_ROI_6_SOBEL5X5_B_0       (0x3CC8UL)
#define ISP_RGB_AFM_ROI_7_SOBEL5X5_R_0       (0x3CCCUL)
#define ISP_RGB_AFM_ROI_7_SOBEL5X5_G_0       (0x3CD0UL)
#define ISP_RGB_AFM_ROI_7_SOBEL5X5_B_0       (0x3CD4UL)
#define ISP_RGB_AFM_ROI_8_SOBEL5X5_R_0       (0x3CD8UL)
#define ISP_RGB_AFM_ROI_8_SOBEL5X5_G_0       (0x3CDCUL)
#define ISP_RGB_AFM_ROI_8_SOBEL5X5_B_0       (0x3CE0UL)
#define ISP_RGB_AFM_ROI_9_SOBEL5X5_R_0       (0x3CE4UL)
#define ISP_RGB_AFM_ROI_9_SOBEL5X5_G_0       (0x3CE8UL)
#define ISP_RGB_AFM_ROI_9_SOBEL5X5_B_0       (0x3CECUL)
#define ISP_RGB_AFM_ROI_0_SOBEL9X9_R_0       (0x3CF0UL)
#define ISP_RGB_AFM_ROI_0_SOBEL9X9_G_0       (0x3CF4UL)
#define ISP_RGB_AFM_ROI_0_SOBEL9X9_B_0       (0x3CF8UL)
#define ISP_RGB_AFM_ROI_1_SOBEL9X9_R_0       (0x3CFCUL)
#define ISP_RGB_AFM_ROI_1_SOBEL9X9_G_0       (0x3D00UL)
#define ISP_RGB_AFM_ROI_1_SOBEL9X9_B_0       (0x3D04UL)
#define ISP_RGB_AFM_ROI_2_SOBEL9X9_R_0       (0x3D08UL)
#define ISP_RGB_AFM_ROI_2_SOBEL9X9_G_0       (0x3D0CUL)
#define ISP_RGB_AFM_ROI_2_SOBEL9X9_B_0       (0x3D10UL)
#define ISP_RGB_AFM_ROI_3_SOBEL9X9_R_0       (0x3D14UL)
#define ISP_RGB_AFM_ROI_3_SOBEL9X9_G_0       (0x3D18UL)
#define ISP_RGB_AFM_ROI_3_SOBEL9X9_B_0       (0x3D1CUL)
#define ISP_RGB_AFM_ROI_4_SOBEL9X9_R_0       (0x3D20UL)
#define ISP_RGB_AFM_ROI_4_SOBEL9X9_G_0       (0x3D24UL)
#define ISP_RGB_AFM_ROI_4_SOBEL9X9_B_0       (0x3D28UL)
#define ISP_RGB_AFM_ROI_5_SOBEL9X9_R_0       (0x3D2CUL)
#define ISP_RGB_AFM_ROI_5_SOBEL9X9_G_0       (0x3D30UL)
#define ISP_RGB_AFM_ROI_5_SOBEL9X9_B_0       (0x3D34UL)
#define ISP_RGB_AFM_ROI_6_SOBEL9X9_R_0       (0x3D38UL)
#define ISP_RGB_AFM_ROI_6_SOBEL9X9_G_0       (0x3D3CUL)
#define ISP_RGB_AFM_ROI_6_SOBEL9X9_B_0       (0x3D40UL)
#define ISP_RGB_AFM_ROI_7_SOBEL9X9_R_0       (0x3D44UL)
#define ISP_RGB_AFM_ROI_7_SOBEL9X9_G_0       (0x3D48UL)
#define ISP_RGB_AFM_ROI_7_SOBEL9X9_B_0       (0x3D4CUL)
#define ISP_RGB_AFM_ROI_8_SOBEL9X9_R_0       (0x3D50UL)
#define ISP_RGB_AFM_ROI_8_SOBEL9X9_G_0       (0x3D54UL)
#define ISP_RGB_AFM_ROI_8_SOBEL9X9_B_0       (0x3D58UL)
#define ISP_RGB_AFM_ROI_9_SOBEL9X9_R_0       (0x3D5CUL)
#define ISP_RGB_AFM_ROI_9_SOBEL9X9_G_0       (0x3D60UL)
#define ISP_RGB_AFM_ROI_9_SOBEL9X9_B_0       (0x3D64UL)
#define ISP_RGB_AFM_ROI_0_SPSMD_R_0          (0x3D68UL)
#define ISP_RGB_AFM_ROI_0_SPSMD_G_0          (0x3D6CUL)
#define ISP_RGB_AFM_ROI_0_SPSMD_B_0          (0x3D70UL)
#define ISP_RGB_AFM_ROI_1_SPSMD_R_0          (0x3D74UL)
#define ISP_RGB_AFM_ROI_1_SPSMD_G_0          (0x3D78UL)
#define ISP_RGB_AFM_ROI_1_SPSMD_B_0          (0x3D7CUL)
#define ISP_RGB_AFM_ROI_2_SPSMD_R_0          (0x3D80UL)
#define ISP_RGB_AFM_ROI_2_SPSMD_G_0          (0x3D84UL)
#define ISP_RGB_AFM_ROI_2_SPSMD_B_0          (0x3D88UL)
#define ISP_RGB_AFM_ROI_3_SPSMD_R_0          (0x3D8CUL)
#define ISP_RGB_AFM_ROI_3_SPSMD_G_0          (0x3D90UL)
#define ISP_RGB_AFM_ROI_3_SPSMD_B_0          (0x3D94UL)
#define ISP_RGB_AFM_ROI_4_SPSMD_R_0          (0x3D98UL)
#define ISP_RGB_AFM_ROI_4_SPSMD_G_0          (0x3D9CUL)
#define ISP_RGB_AFM_ROI_4_SPSMD_B_0          (0x3DA0UL)
#define ISP_RGB_AFM_ROI_5_SPSMD_R_0          (0x3DA4UL)
#define ISP_RGB_AFM_ROI_5_SPSMD_G_0          (0x3DA8UL)
#define ISP_RGB_AFM_ROI_5_SPSMD_B_0          (0x3DACUL)
#define ISP_RGB_AFM_ROI_6_SPSMD_R_0          (0x3DB0UL)
#define ISP_RGB_AFM_ROI_6_SPSMD_G_0          (0x3DB4UL)
#define ISP_RGB_AFM_ROI_6_SPSMD_B_0          (0x3DB8UL)
#define ISP_RGB_AFM_ROI_7_SPSMD_R_0          (0x3DBCUL)
#define ISP_RGB_AFM_ROI_7_SPSMD_G_0          (0x3DC0UL)
#define ISP_RGB_AFM_ROI_7_SPSMD_B_0          (0x3DC4UL)
#define ISP_RGB_AFM_ROI_8_SPSMD_R_0          (0x3DC8UL)
#define ISP_RGB_AFM_ROI_8_SPSMD_G_0          (0x3DCCUL)
#define ISP_RGB_AFM_ROI_8_SPSMD_B_0          (0x3DD0UL)
#define ISP_RGB_AFM_ROI_9_SPSMD_R_0          (0x3DD4UL)
#define ISP_RGB_AFM_ROI_9_SPSMD_G_0          (0x3DD8UL)
#define ISP_RGB_AFM_ROI_9_SPSMD_B_0          (0x3DDCUL)
#define ISP_RGB_AFM_SOBEL5_THR_G             (0x3DE0UL)
#define ISP_RGB_AFM_SOBEL9_THR_G             (0x3DE4UL)
#define ISP_RGB_AFM_SPSMD_THR_G              (0x3DE8UL)
#define ISP_RGB_AFM_SOBEL5_THR_B             (0x3DECUL)
#define ISP_RGB_AFM_SOBEL9_THR_B             (0x3DF0UL)
#define ISP_RGB_AFM_SPSMD_THR_B              (0x3DF4UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_01_R_0      (0x3DF8UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_23_R_0      (0x3DFCUL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_45_R_0      (0x3E00UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_67_R_0      (0x3E04UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_89_R_0      (0x3E08UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_01_G_0      (0x3E0CUL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_23_G_0      (0x3E10UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_45_G_0      (0x3E14UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_67_G_0      (0x3E18UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_89_G_0      (0x3E1CUL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_01_B_0      (0x3E20UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_23_B_0      (0x3E24UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_45_B_0      (0x3E28UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_67_B_0      (0x3E2CUL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_89_B_0      (0x3E30UL)
#define ISP_RGB_AFM_ROI_0_SOBEL5X5_R_1       (0x3E34UL)
#define ISP_RGB_AFM_ROI_0_SOBEL5X5_G_1       (0x3E38UL)
#define ISP_RGB_AFM_ROI_0_SOBEL5X5_B_1       (0x3E3CUL)
#define ISP_RGB_AFM_ROI_1_SOBEL5X5_R_1       (0x3E40UL)
#define ISP_RGB_AFM_ROI_1_SOBEL5X5_G_1       (0x3E44UL)
#define ISP_RGB_AFM_ROI_1_SOBEL5X5_B_1       (0x3E48UL)
#define ISP_RGB_AFM_ROI_2_SOBEL5X5_R_1       (0x3E4CUL)
#define ISP_RGB_AFM_ROI_2_SOBEL5X5_G_1       (0x3E50UL)
#define ISP_RGB_AFM_ROI_2_SOBEL5X5_B_1       (0x3E54UL)
#define ISP_RGB_AFM_ROI_3_SOBEL5X5_R_1       (0x3E58UL)
#define ISP_RGB_AFM_ROI_3_SOBEL5X5_G_1       (0x3E5CUL)
#define ISP_RGB_AFM_ROI_3_SOBEL5X5_B_1       (0x3E60UL)
#define ISP_RGB_AFM_ROI_4_SOBEL5X5_R_1       (0x3E64UL)
#define ISP_RGB_AFM_ROI_4_SOBEL5X5_G_1       (0x3E68UL)
#define ISP_RGB_AFM_ROI_4_SOBEL5X5_B_1       (0x3E6CUL)
#define ISP_RGB_AFM_ROI_5_SOBEL5X5_R_1       (0x3E70UL)
#define ISP_RGB_AFM_ROI_5_SOBEL5X5_G_1       (0x3E74UL)
#define ISP_RGB_AFM_ROI_5_SOBEL5X5_B_1       (0x3E78UL)
#define ISP_RGB_AFM_ROI_6_SOBEL5X5_R_1       (0x3E7CUL)
#define ISP_RGB_AFM_ROI_6_SOBEL5X5_G_1       (0x3E80UL)
#define ISP_RGB_AFM_ROI_6_SOBEL5X5_B_1       (0x3E84UL)
#define ISP_RGB_AFM_ROI_7_SOBEL5X5_R_1       (0x3E88UL)
#define ISP_RGB_AFM_ROI_7_SOBEL5X5_G_1       (0x3E8CUL)
#define ISP_RGB_AFM_ROI_7_SOBEL5X5_B_1       (0x3E90UL)
#define ISP_RGB_AFM_ROI_8_SOBEL5X5_R_1       (0x3E94UL)
#define ISP_RGB_AFM_ROI_8_SOBEL5X5_G_1       (0x3E98UL)
#define ISP_RGB_AFM_ROI_8_SOBEL5X5_B_1       (0x3E9CUL)
#define ISP_RGB_AFM_ROI_9_SOBEL5X5_R_1       (0x3EA0UL)
#define ISP_RGB_AFM_ROI_9_SOBEL5X5_G_1       (0x3EA4UL)
#define ISP_RGB_AFM_ROI_9_SOBEL5X5_B_1       (0x3EA8UL)
#define ISP_RGB_AFM_ROI_0_SOBEL9X9_R_1       (0x3EACUL)
#define ISP_RGB_AFM_ROI_0_SOBEL9X9_G_1       (0x3EB0UL)
#define ISP_RGB_AFM_ROI_0_SOBEL9X9_B_1       (0x3EB4UL)
#define ISP_RGB_AFM_ROI_1_SOBEL9X9_R_1       (0x3EB8UL)
#define ISP_RGB_AFM_ROI_1_SOBEL9X9_G_1       (0x3EBCUL)
#define ISP_RGB_AFM_ROI_1_SOBEL9X9_B_1       (0x3EC0UL)
#define ISP_RGB_AFM_ROI_2_SOBEL9X9_R_1       (0x3EC4UL)
#define ISP_RGB_AFM_ROI_2_SOBEL9X9_G_1       (0x3EC8UL)
#define ISP_RGB_AFM_ROI_2_SOBEL9X9_B_1       (0x3ECCUL)
#define ISP_RGB_AFM_ROI_3_SOBEL9X9_R_1       (0x3ED0UL)
#define ISP_RGB_AFM_ROI_3_SOBEL9X9_G_1       (0x3ED4UL)
#define ISP_RGB_AFM_ROI_3_SOBEL9X9_B_1       (0x3ED8UL)
#define ISP_RGB_AFM_ROI_4_SOBEL9X9_R_1       (0x3EDCUL)
#define ISP_RGB_AFM_ROI_4_SOBEL9X9_G_1       (0x3EE0UL)
#define ISP_RGB_AFM_ROI_4_SOBEL9X9_B_1       (0x3EE4UL)
#define ISP_RGB_AFM_ROI_5_SOBEL9X9_R_1       (0x3EE8UL)
#define ISP_RGB_AFM_ROI_5_SOBEL9X9_G_1       (0x3EECUL)
#define ISP_RGB_AFM_ROI_5_SOBEL9X9_B_1       (0x3EF0UL)
#define ISP_RGB_AFM_ROI_6_SOBEL9X9_R_1       (0x3EF4UL)
#define ISP_RGB_AFM_ROI_6_SOBEL9X9_G_1       (0x3EF8UL)
#define ISP_RGB_AFM_ROI_6_SOBEL9X9_B_1       (0x3EFCUL)
#define ISP_RGB_AFM_ROI_7_SOBEL9X9_R_1       (0x3F00UL)
#define ISP_RGB_AFM_ROI_7_SOBEL9X9_G_1       (0x3F04UL)
#define ISP_RGB_AFM_ROI_7_SOBEL9X9_B_1       (0x3F08UL)
#define ISP_RGB_AFM_ROI_8_SOBEL9X9_R_1       (0x3F0CUL)
#define ISP_RGB_AFM_ROI_8_SOBEL9X9_G_1       (0x3F10UL)
#define ISP_RGB_AFM_ROI_8_SOBEL9X9_B_1       (0x3F14UL)
#define ISP_RGB_AFM_ROI_9_SOBEL9X9_R_1       (0x3F18UL)
#define ISP_RGB_AFM_ROI_9_SOBEL9X9_G_1       (0x3F1CUL)
#define ISP_RGB_AFM_ROI_9_SOBEL9X9_B_1       (0x3F20UL)
#define ISP_RGB_AFM_ROI_0_SPSMD_R_1          (0x3F24UL)
#define ISP_RGB_AFM_ROI_0_SPSMD_G_1          (0x3F28UL)
#define ISP_RGB_AFM_ROI_0_SPSMD_B_1          (0x3F2CUL)
#define ISP_RGB_AFM_ROI_1_SPSMD_R_1          (0x3F30UL)
#define ISP_RGB_AFM_ROI_1_SPSMD_G_1          (0x3F34UL)
#define ISP_RGB_AFM_ROI_1_SPSMD_B_1          (0x3F38UL)
#define ISP_RGB_AFM_ROI_2_SPSMD_R_1          (0x3F3CUL)
#define ISP_RGB_AFM_ROI_2_SPSMD_G_1          (0x3F40UL)
#define ISP_RGB_AFM_ROI_2_SPSMD_B_1          (0x3F44UL)
#define ISP_RGB_AFM_ROI_3_SPSMD_R_1          (0x3F48UL)
#define ISP_RGB_AFM_ROI_3_SPSMD_G_1          (0x3F4CUL)
#define ISP_RGB_AFM_ROI_3_SPSMD_B_1          (0x3F50UL)
#define ISP_RGB_AFM_ROI_4_SPSMD_R_1          (0x3F54UL)
#define ISP_RGB_AFM_ROI_4_SPSMD_G_1          (0x3F58UL)
#define ISP_RGB_AFM_ROI_4_SPSMD_B_1          (0x3F5CUL)
#define ISP_RGB_AFM_ROI_5_SPSMD_R_1          (0x3F60UL)
#define ISP_RGB_AFM_ROI_5_SPSMD_G_1          (0x3F64UL)
#define ISP_RGB_AFM_ROI_5_SPSMD_B_1          (0x3F68UL)
#define ISP_RGB_AFM_ROI_6_SPSMD_R_1          (0x3F6CUL)
#define ISP_RGB_AFM_ROI_6_SPSMD_G_1          (0x3F70UL)
#define ISP_RGB_AFM_ROI_6_SPSMD_B_1          (0x3F74UL)
#define ISP_RGB_AFM_ROI_7_SPSMD_R_1          (0x3F78UL)
#define ISP_RGB_AFM_ROI_7_SPSMD_G_1          (0x3F7CUL)
#define ISP_RGB_AFM_ROI_7_SPSMD_B_1          (0x3F80UL)
#define ISP_RGB_AFM_ROI_8_SPSMD_R_1          (0x3F84UL)
#define ISP_RGB_AFM_ROI_8_SPSMD_G_1          (0x3F88UL)
#define ISP_RGB_AFM_ROI_8_SPSMD_B_1          (0x3F8CUL)
#define ISP_RGB_AFM_ROI_9_SPSMD_R_1          (0x3F90UL)
#define ISP_RGB_AFM_ROI_9_SPSMD_G_1          (0x3F94UL)
#define ISP_RGB_AFM_ROI_9_SPSMD_B_1          (0x3F98UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_01_R_1      (0x3F9CUL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_23_R_1      (0x3FA0UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_45_R_1      (0x3FA4UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_67_R_1      (0x3FA8UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_89_R_1      (0x3FACUL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_01_G_1      (0x3FB0UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_23_G_1      (0x3FB4UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_45_G_1      (0x3FB8UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_67_G_1      (0x3FBCUL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_89_G_1      (0x3FC0UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_01_B_1      (0x3FC4UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_23_B_1      (0x3FC8UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_45_B_1      (0x3FCCUL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_67_B_1      (0x3FD0UL)
#define ISP_RGB_AFM_HIGH_BIT_ROI_89_B_1      (0x3FD4UL)

/*isp sub block:ANTI FLICKER*/
#define ISP_ANTI_FLICKER_STATUS0           (0x4200UL)
#define ISP_ANTI_FLICKER_STATUS1           (0x4204UL)
#define ISP_ANTI_FLICKER_PARAM0            (0x4214UL)
#define ISP_ANTI_FLICKER_PARAM1            (0x4218UL)
#define ISP_ANTI_FLICKER_COL_POS           (0x421CUL)
#define ISP_ANTI_FLICKER_DDR_INIT_ADDR     (0x4220UL)

/*isp sub block:ANTI FLICKER NEW*/
#define ISP_ANTI_FLICKER_NEW_STATUS0       (0x4600UL)
#define ISP_ANTI_FLICKER_NEW_STATUS1       (0x4604UL)
#define ISP_ANTI_FLICKER_NEW_STATUS2       (0x4608UL)
#define ISP_ANTI_FLICKER_NEW_PARAM0        (0x4614UL)
#define ISP_ANTI_FLICKER_NEW_PARAM1        (0x4618UL)
#define ISP_ANTI_FLICKER_NEW_PARAM2        (0x461CUL)
#define ISP_ANTI_FLICKER_NEW_COL_POS       (0x4620UL)
#define ISP_ANTI_FLICKER_NEW_DDR_INIT_ADDR (0x4624UL)

/*isp sub block: Pre-CDN*/
#define ISP_PRECDN_STATUS0                 (0x5000UL)
#define ISP_PRECDN_STATUS1                 (0x5004UL)
#define ISP_PRECDN_PARAM                   (0x5014UL)
#define ISP_PRECDN_MEDIAN_THRUV01          (0x5018UL)
#define ISP_PRECDN_THRYUV                  (0x501CUL)
#define ISP_PRECDN_SEGU_0                  (0x5020UL)
#define ISP_PRECDN_SEGU_1                  (0x5024UL)
#define ISP_PRECDN_SEGU_2                  (0x5028UL)
#define ISP_PRECDN_SEGU_3                  (0x502CUL)
#define ISP_PRECDN_SEGV_0                  (0x5030UL)
#define ISP_PRECDN_SEGV_1                  (0x5034UL)
#define ISP_PRECDN_SEGV_2                  (0x5038UL)
#define ISP_PRECDN_SEGV_3                  (0x503CUL)
#define ISP_PRECDN_SEGY_0                  (0x5040UL)
#define ISP_PRECDN_SEGY_1                  (0x5044UL)
#define ISP_PRECDN_SEGY_2                  (0x5048UL)
#define ISP_PRECDN_SEGY_3                  (0x504CUL)
#define ISP_PRECDN_DISTW0                  (0x5050UL)
#define ISP_PRECDN_DISTW1                  (0x5054UL)
#define ISP_PRECDN_DISTW2                  (0x5058UL)
#define ISP_PRECDN_DISTW3                  (0x505CUL)

/*isp sub block: Pre-Filter*/
#define ISP_PREF_STATUS0                   (0x5100UL)
#define ISP_PREF_STATUS1                   (0x5104UL)
#define ISP_PREF_PARAM                     (0x5114UL)
#define ISP_PREF_THRD                      (0x5118UL)

/*isp sub block: Brightness*/
#define ISP_BRIGHT_STATUS                  (0x5300UL)
#define ISP_BRIGHT_PARAM                   (0x5314UL)

/*isp sub block: HIST : histogram*/
#define ISP_HIST_STATUS                    (0x5500UL)
#define ISP_HIST_PARAM                     (0x5514UL)
#define ISP_HIST_SKIP_NUM_CLR              (0x5518UL)
#define ISP_HIST_BUF_RST_EN                (0x551CUL)

/*isp sub block: HIST2*/
#define ISP_HIST2_STATUS                   (0x5600UL)
#define ISP_HIST2_PARAM                    (0x5614UL)
#define ISP_HIST2_ROI_S0                   (0x5618UL)
#define ISP_HIST2_ROI_E0                   (0x561CUL)
#define ISP_HIST2_SKIP_NUM_CLR             (0x5620UL)
#define ISP_HIST2_BUF_RST_EN               (0x5624UL)

/*isp sub block: cdn*/
#define ISP_CDN_STATUS0                    (0x5800UL)
#define ISP_CDN_STATUS1                    (0x5804UL)
#define ISP_CDN_PARAM                      (0x5814UL)
#define ISP_CDN_THRUV                      (0x5818UL)
#define ISP_CDN_U_RANWEI_0                 (0x581CUL)
#define ISP_CDN_U_RANWEI_1                 (0x5820UL)
#define ISP_CDN_U_RANWEI_2                 (0x5824UL)
#define ISP_CDN_U_RANWEI_3                 (0x5828UL)
#define ISP_CDN_U_RANWEI_4                 (0x582CUL)
#define ISP_CDN_U_RANWEI_5                 (0x5830UL)
#define ISP_CDN_U_RANWEI_6                 (0x5834UL)
#define ISP_CDN_U_RANWEI_7                 (0x5838UL)
#define ISP_CDN_V_RANWEI_0                 (0x583CUL)
#define ISP_CDN_V_RANWEI_1                 (0x5840UL)
#define ISP_CDN_V_RANWEI_2                 (0x5844UL)
#define ISP_CDN_V_RANWEI_3                 (0x5848UL)
#define ISP_CDN_V_RANWEI_4                 (0x584CUL)
#define ISP_CDN_V_RANWEI_5                 (0x5850UL)
#define ISP_CDN_V_RANWEI_6                 (0x5854UL)
#define ISP_CDN_V_RANWEI_7                 (0x5858UL)

/*isp sub block: edge*/
#define ISP_EE_STATUS                      (0x5900UL)
#define ISP_EE_PARAM                       (0x5914UL)
#define ISP_EE_CFG0                        (0x5918UL)
#define ISP_EE_CFG1                        (0x591CUL)
#define ISP_EE_CFG2                        (0x5920UL)
#define ISP_EE_CFG3                        (0x5924UL)
#define ISP_EE_CFG4                        (0x5928UL)
#define ISP_EE_CFG5                        (0x592CUL)
#define ISP_EE_CFG6                        (0x5930UL)
#define ISP_EE_CFG7                        (0x5934UL)
#define ISP_EE_ADP_CFG0                    (0x5938UL)
#define ISP_EE_ADP_CFG1                    (0x593CUL)
#define ISP_EE_ADP_CFG2                    (0x5940UL)

/*isp sub block: CSS*/
#define ISP_CSS_STATUS                     (0x5B00UL)
#define ISP_CSS_PARAM                      (0x5B14UL)
#define ISP_CSS_THRD0                      (0x5B18UL)
#define ISP_CSS_LH_RATIO                   (0x5B1CUL)
#define ISP_CSS_EX_TH_0                    (0x5B20UL)
#define ISP_CSS_EX_TH_1                    (0x5B24UL)
#define ISP_CSS_CHROM_L_TH_0               (0x5B28UL)
#define ISP_CSS_CHROM_L_TH_1               (0x5B2CUL)
#define ISP_CSS_CHROM_H_TH_0               (0x5B30UL)
#define ISP_CSS_CHROM_H_TH_1               (0x5B34UL)
#define ISP_CSS_RATIO                      (0x5B38UL)

/*isp sub block: csa*/
#define ISP_CSA_STATUS                     (0x5C00UL)
#define ISP_CSA_PARAM                      (0x5C14UL)

/*isp sub block: hua*/
#define ISP_HUA_STATUS                     (0x5D00UL)
#define ISP_HUA_PARAM                      (0x5D14UL)

/*isp sub block: post-cdn*/
#define ISP_POSTCDN_STATUS                 (0x5E00UL)
#define ISP_POSTCDN_COMMON_CTRL            (0x5E14UL)
#define ISP_POSTCDN_ADPT_THR               (0x5E18UL)
#define ISP_POSTCDN_UVTHR                  (0x5E1CUL)
#define ISP_POSTCDN_THRU                   (0x5E20UL)
#define ISP_POSTCDN_THRV                   (0x5E24UL)
#define ISP_POSTCDN_RSEGU01                (0x5E28UL)
#define ISP_POSTCDN_RSEGU23                (0x5E2CUL)
#define ISP_POSTCDN_RSEGU45                (0x5E30UL)
#define ISP_POSTCDN_RSEGU6                 (0x5E34UL)
#define ISP_POSTCDN_RSEGV01                (0x5E38UL)
#define ISP_POSTCDN_RSEGV23                (0x5E3CUL)
#define ISP_POSTCDN_RSEGV45                (0x5E40UL)
#define ISP_POSTCDN_RSEGV6                 (0x5E44UL)
#define ISP_POSTCDN_R_DISTW0               (0x5E48UL)
#define ISP_POSTCDN_R_DISTW1               (0x5E4CUL)
#define ISP_POSTCDN_R_DISTW2               (0x5E50UL)
#define ISP_POSTCDN_R_DISTW3               (0x5E54UL)
#define ISP_POSTCDN_R_DISTW4               (0x5E58UL)
#define ISP_POSTCDN_R_DISTW5               (0x5E5CUL)
#define ISP_POSTCDN_R_DISTW6               (0x5E60UL)
#define ISP_POSTCDN_R_DISTW7               (0x5E64UL)
#define ISP_POSTCDN_R_DISTW8               (0x5E68UL)
#define ISP_POSTCDN_R_DISTW9               (0x5E6CUL)
#define ISP_POSTCDN_R_DISTW10              (0x5E70UL)
#define ISP_POSTCDN_R_DISTW11              (0x5E74UL)
#define ISP_POSTCDN_R_DISTW12              (0x5E78UL)
#define ISP_POSTCDN_R_DISTW13              (0x5E7CUL)
#define ISP_POSTCDN_R_DISTW14              (0x5E80UL)
#define ISP_POSTCDN_START_ROW_MOD4         (0x5E84UL)

/*isp sub block: ygamma*/
#define ISP_YGAMMA_STATUS                  (0x6000UL)
#define ISP_YGAMMA_PARAM                   (0x6014UL)

/*isp sub block: ydelay*/
#define ISP_YDELAY_STATUS                  (0x6100UL)
#define ISP_YDELAY_PARAM                   (0x6114UL)

/*isp sub block: iircnr*/
#define ISP_IIRCNR_STATUS0                 (0x6400UL)
#define ISP_IIRCNR_STATUS1                 (0x6404UL)
#define ISP_IIRCNR_PARAM                   (0x6414UL)
#define ISP_IIRCNR_PARAM1                  (0x6418UL)
#define ISP_IIRCNR_PARAM2                  (0x6420UL)
#define ISP_IIRCNR_PARAM3                  (0x6424UL)
#define ISP_IIRCNR_PARAM4                  (0x6428UL)
#define ISP_IIRCNR_PARAM5                  (0x6430UL)
#define ISP_IIRCNR_PARAM6                  (0x6434UL)
#define ISP_IIRCNR_PARAM7                  (0x6438UL)
#define ISP_IIRCNR_PARAM8                  (0x6440UL)
#define ISP_IIRCNR_PARAM9                  (0x6444UL)

/*isp sub block: yuv yrandom*/
#define ISP_YRANDOM_STATUS0                (0x6500UL)
#define ISP_YRANDOM_CHKSUM                 (0x6504UL)
#define ISP_YRANDOM_PARAM0                 (0x6508UL)
#define ISP_YRANDOM_PARAM1                 (0x6514UL)
#define ISP_YRANDOM_PARAM2                 (0x6518UL)
#define ISP_YRANDOM_PARAM3                 (0x6520UL)
#define ISP_YRANDOM_STATUS1                (0x6524UL)
#define ISP_YRANDOM_STATUS2                (0x6528UL)
#define ISP_YRANDOM_INIT                   (0x6530UL)

/*memory map*/
#define ISP_AWBM_CH0                (0x10000)
#define ISP_AEM_CH0                 (0x12000)
#define ISP_HIST_CH0                (0x15000)
#define ISP_HIST2_CH0                (0x16000)
#define ISP_HSV_BUF0_CH0                   (0x18000UL)
#define ISP_VST_BUF0_CH0                   (0x19000UL)
#define ISP_IVST_BUF0_CH0                  (0x1A000UL)
#define ISP_FGAMMA_R_BUF0_CH0              (0x1B000UL)
#define ISP_FGAMMA_G_BUF0_CH0              (0x1C000UL)
#define ISP_FGAMMA_B_BUF0_CH0              (0x1D000UL)
#define ISP_YGAMMA_BUF0_CH0                (0x1E000UL)
#define ISP_NLM_BUF0_CH0                   (0x1F000UL)
#define ISP_HSV_BUF1_CH0                   (0x21000UL)
#define ISP_VST_BUF1_CH0                   (0x22000UL)
#define ISP_IVST_BUF1_CH0                  (0x23000UL)
#define ISP_FGAMMA_R_BUF1_CH0              (0x24000UL)
#define ISP_FGAMMA_G_BUF1_CH0              (0x25000UL)
#define ISP_FGAMMA_B_BUF1_CH0              (0x26000UL)
#define ISP_YGAMMA_BUF1_CH0                (0x27000UL)
#define ISP_NLM_BUF1_CH0                   (0x28000UL)
#define ISP_LEN_BUF0_CH0                   (0x29000UL)
#define ISP_LEN_BUF1_CH0                   (0x2c000UL)
#define ISP_AFL_BUF_PING                     (0x2f000UL)
#define ISP_AFL_BUF_PANG                  (0x30000UL)

#define ISP_GET_REG(reg)  (ISP_BASE_ADDR + reg)
#define ISP_REG_WR(reg, val)  (REG_WR(ISP_BASE_ADDR+reg, val))
#define ISP_REG_RD(reg)  (REG_RD(ISP_BASE_ADDR+reg))
#define ISP_REG_MWR(reg, msk, val)  ISP_REG_WR(reg, \
		((val)&(msk))|(ISP_REG_RD(reg)&(~(msk))))
#define ISP_REG_OWR(reg, val)  \
		ISP_REG_WR(reg, (ISP_REG_RD(reg)|val))

#define ISP_LOW_CLOCK_WIDTH 1800

#endif
