/*
 * Copyright (C) 2017 Spreadtrum Communications Inc.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 * updated at 2017-10-12 09:49:25
 *
 */


#ifndef ANLG_PHY_G2_H
#define ANLG_PHY_G2_H



#define REG_ANLG_PHY_G2_ANALOG_USB20_USB20_TEST_PIN           (0x0000)
#define REG_ANLG_PHY_G2_ANALOG_USB20_USB20_UTMI_CTL           (0x0004)
#define REG_ANLG_PHY_G2_ANALOG_USB20_USB20_BATTER_PLL         (0x0008)
#define REG_ANLG_PHY_G2_ANALOG_USB20_USB20_TRIMMING           (0x000C)
#define REG_ANLG_PHY_G2_ANALOG_USB20_USB20_PHY_BIST_TEST      (0x0010)
#define REG_ANLG_PHY_G2_ANALOG_USB20_REG_SEL_CFG_0            (0x0014)

/* REG_ANLG_PHY_G2_ANALOG_USB20_USB20_TEST_PIN */

#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TESTCLK                 BIT(24)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TESTDATAIN(x)           (((x) & 0xFF) << 16)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TESTADDR(x)             (((x) & 0xF) << 12)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TESTDATAOUTSEL          BIT(11)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TESTDATAOUT(x)          (((x) & 0xF) << 7)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BIST_MODE(x)            (((x) & 0x1F) << 2)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_T2RCOMP                 BIT(1)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_LPBK_END                BIT(0)

/* REG_ANLG_PHY_G2_ANALOG_USB20_USB20_UTMI_CTL */

#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_DATABUS16_8             BIT(28)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_SUSPENDM                BIT(27)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_PORN                    BIT(26)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_RESET                   BIT(25)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_RXERROR                 BIT(24)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BYPASS_DRV_DP           BIT(23)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BYPASS_DRV_DM           BIT(22)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BYPASS_FS               BIT(21)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BYPASS_IN_DP            BIT(20)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BYPASS_IN_DM            BIT(19)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BYPASS_OUT_DP           BIT(18)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BYPASS_OUT_DM           BIT(17)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_VBUSVLDEXT              BIT(16)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_RESERVED(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G2_ANALOG_USB20_USB20_BATTER_PLL */

#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_PS_PD_S                 BIT(5)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_PS_PD_L                 BIT(4)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_REXTENABLE              BIT(3)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_DMPULLUP                BIT(2)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_HSIC_PLLON                    BIT(1)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_SAMPLER_SEL             BIT(0)

/* REG_ANLG_PHY_G2_ANALOG_USB20_USB20_TRIMMING */

#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TUNEHSAMP(x)            (((x) & 0x3) << 27)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TFREGRES(x)             (((x) & 0x3F) << 21)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TFHSRES(x)              (((x) & 0x1F) << 16)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TUNERISE(x)             (((x) & 0x3) << 14)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TUNEOTG(x)              (((x) & 0x7) << 11)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TUNEDSC(x)              (((x) & 0x3) << 9)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TUNESQ(x)               (((x) & 0xF) << 5)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TUNEEQ(x)               (((x) & 0x7) << 2)
#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_TUNEPLLS(x)             (((x) & 0x3))

/* REG_ANLG_PHY_G2_ANALOG_USB20_USB20_PHY_BIST_TEST */

#define BIT_ANLG_PHY_G2_ANALOG_USB20_USB20_BIST_MODE_EN            BIT(0)

/* REG_ANLG_PHY_G2_ANALOG_USB20_REG_SEL_CFG_0 */

#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TESTCLK         BIT(30)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TESTDATAIN      BIT(29)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TESTADDR        BIT(28)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TESTDATAOUTSEL  BIT(27)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_BIST_MODE       BIT(26)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_DATABUS16_8     BIT(25)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_SUSPENDM        BIT(24)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_PORN            BIT(23)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_RESET           BIT(22)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_BYPASS_DRV_DP   BIT(21)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_BYPASS_DRV_DM   BIT(20)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_BYPASS_FS       BIT(19)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_BYPASS_IN_DP    BIT(18)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_BYPASS_IN_DM    BIT(17)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_VBUSVLDEXT      BIT(16)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_RESERVED        BIT(15)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_PS_PD_S         BIT(14)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_PS_PD_L         BIT(13)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_REXTENABLE      BIT(12)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_DMPULLUP        BIT(11)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_HSIC_PLLON            BIT(10)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_SAMPLER_SEL     BIT(9)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TUNEHSAMP       BIT(8)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TFREGRES        BIT(7)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TFHSRES         BIT(6)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TUNERISE        BIT(5)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TUNEOTG         BIT(4)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TUNEDSC         BIT(3)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TUNESQ          BIT(2)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TUNEEQ          BIT(1)
#define BIT_ANLG_PHY_G2_DBG_SEL_ANALOG_USB20_USB20_TUNEPLLS        BIT(0)


#endif /* ANLG_PHY_G2_H */

