/*
 * Copyright (C) 2017 Spreadtrum Communications Inc.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 * updated at 2017-10-12 09:49:25
 *
 */


#ifndef ANLG_PHY_G1_H
#define ANLG_PHY_G1_H



#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_ANA_BB_PWR_CTRL      (0x0000)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_ANA_BB_RST_CTRL      (0x0004)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_ANALOG_PLL_RES       (0x0008)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_CTRL0           (0x000C)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_CTRL1           (0x0010)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_CTRL2           (0x0014)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_BIST_CTRL       (0x0018)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_CTRL0           (0x001C)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_CTRL1           (0x0020)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_CTRL2           (0x0024)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_BIST_CTRL       (0x0028)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_CTRL0          (0x002C)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_CTRL1          (0x0030)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_CTRL2          (0x0034)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_BIST_CTRL      (0x0038)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_CTRL0          (0x003C)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_CTRL1          (0x0040)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_CTRL2          (0x0044)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_BIST_CTRL      (0x0048)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_CTRL0           (0x004C)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_CTRL1           (0x0050)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_CTRL2           (0x0054)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_BIST_CTRL       (0x0058)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_THM_CTRL_0           (0x005C)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_THM_CTRL_1           (0x0060)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_ANA_BB_RSVD          (0x0064)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_TEST_CLK_CTRL        (0x0068)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_REG_SEL_CFG_0        (0x006C)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_REG_SEL_CFG_1        (0x0070)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_REG_SEL_CFG_2        (0x0074)
#define REG_ANLG_PHY_G1_ANALOG_BB_TOP_REG_SEL_CFG_3        (0x0078)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_ANA_BB_PWR_CTRL */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_PD                      BIT(5)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_PD                      BIT(4)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_PD                     BIT(3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_PD                     BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_PD                      BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_PD                       BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_ANA_BB_RST_CTRL */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_RST                     BIT(5)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_RST                     BIT(4)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_RST                    BIT(3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_RST                    BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_RST                     BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_RSTN                     BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_ANALOG_PLL_RES */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_ANALOG_PLL_RESERVED(x)       (((x) & 0xFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_CTRL0 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_REF_SEL                 BIT(22)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_N(x)                    (((x) & 0x7FF) << 11)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_IBIAS(x)                (((x) & 0x3) << 9)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_SDM_EN                  BIT(8)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_MOD_EN                  BIT(7)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_DIV_S                   BIT(6)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_RESERVED(x)             (((x) & 0xF) << 2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_CLKOUT_EN               BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_LOCK_DONE               BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_CTRL1 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_NINT(x)                 (((x) & 0x7F) << 23)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_KINT(x)                 (((x) & 0x7FFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_CTRL2 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_CCS_CTRL(x)             (((x) & 0xFF) << 3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_IL_DIV2                 BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_OL_DIV2                 BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_TEST_EN                 BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_BIST_CTRL */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_BIST_EN                 BIT(16)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_DPLL_BIST_CNT(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_CTRL0 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_REF_SEL                 BIT(22)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_N(x)                    (((x) & 0x7FF) << 11)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_IBIAS(x)                (((x) & 0x3) << 9)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_SDM_EN                  BIT(8)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_MOD_EN                  BIT(7)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_DIV_S                   BIT(6)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_RESERVED(x)             (((x) & 0xF) << 2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_CLKOUT_EN               BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_LOCK_DONE               BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_CTRL1 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_NINT(x)                 (((x) & 0x7F) << 23)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_KINT(x)                 (((x) & 0x7FFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_CTRL2 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_CCS_CTRL(x)             (((x) & 0xFF) << 3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_IL_DIV2                 BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_OL_DIV2                 BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_TEST_EN                 BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_BIST_CTRL */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_BIST_EN                 BIT(16)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_MPLL_BIST_CNT(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_CTRL0 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_REF_SEL                BIT(27)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_N(x)                   (((x) & 0x7FF) << 16)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_IBIAS(x)               (((x) & 0x3) << 14)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_SDM_EN                 BIT(13)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_MOD_EN                 BIT(12)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_DIV_S                  BIT(11)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_RESERVED(x)            (((x) & 0xF) << 7)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_CLKOUT_EN              BIT(6)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_DIV1_EN                BIT(5)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_DIV2_EN                BIT(4)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_DIV3_EN                BIT(3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_DIV5_EN                BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_DIV7_EN                BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_LOCK_DONE              BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_CTRL1 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_NINT(x)                (((x) & 0x7F) << 23)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_KINT(x)                (((x) & 0x7FFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_CTRL2 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_CCS_CTRL(x)            (((x) & 0xFF) << 3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_IL_DIV2                BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_OL_DIV2                BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_TEST_EN                BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_BIST_CTRL */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_BIST_EN                BIT(16)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TWPLL_BIST_CNT(x)            (((x) & 0xFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_CTRL0 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_REF_SEL                BIT(27)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_N(x)                   (((x) & 0x7FF) << 16)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_IBIAS(x)               (((x) & 0x3) << 14)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_SDM_EN                 BIT(13)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_MOD_EN                 BIT(12)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_DIV_S                  BIT(11)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_RESERVED(x)            (((x) & 0xF) << 7)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_CLKOUT_EN              BIT(6)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_DIV1_EN                BIT(5)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_DIV2_EN                BIT(4)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_DIV3_EN                BIT(3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_DIV5_EN                BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_DIV7_EN                BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_LOCK_DONE              BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_CTRL1 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_NINT(x)                (((x) & 0x7F) << 23)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_KINT(x)                (((x) & 0x7FFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_CTRL2 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_CCS_CTRL(x)            (((x) & 0xFF) << 3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_IL_DIV2                BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_OL_DIV2                BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_TEST_EN                BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_BIST_CTRL */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_BIST_EN                BIT(16)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_CPPLL_BIST_CNT(x)            (((x) & 0xFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_CTRL0 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_REF_SEL                 BIT(22)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_N(x)                    (((x) & 0x7FF) << 11)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_IBIAS(x)                (((x) & 0x3) << 9)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_SDM_EN                  BIT(8)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_MOD_EN                  BIT(7)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_DIV_S                   BIT(6)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_RESERVED(x)             (((x) & 0xF) << 2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_CLKOUT_EN               BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_LOCK_DONE               BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_CTRL1 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_NINT(x)                 (((x) & 0x7F) << 23)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_KINT(x)                 (((x) & 0x7FFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_CTRL2 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_CCS_CTRL(x)             (((x) & 0xFF) << 3)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_IL_DIV2                 BIT(2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_OL_DIV2                 BIT(1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_TEST_EN                 BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_BIST_CTRL */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_BIST_EN                 BIT(16)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_GPLL_BIST_CNT(x)             (((x) & 0xFFFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_THM_CTRL_0 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_RUN                      BIT(20)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_RESERVED(x)              (((x) & 0xFF) << 12)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_BG_RBIAS_MODE            BIT(11)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_TEST_SEL(x)              (((x) & 0x3) << 9)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_BP_MODE                  BIT(8)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_BP_DATA(x)               (((x) & 0xFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_THM_CTRL_1 */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_DATA(x)                  (((x) & 0xFF) << 1)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_THM_VALID                    BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_ANA_BB_RSVD */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_ANA_BB_RESERVED(x)           (((x) & 0xFF))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_TEST_CLK_CTRL */

#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TEST_PLL_THM_MUX(x)          (((x) & 0x1F) << 2)
#define BIT_ANLG_PHY_G1_ANALOG_BB_TOP_TEST_CLK_DIV(x)              (((x) & 0x3))

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_REG_SEL_CFG_0 */

#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_PD              BIT(31)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_PD              BIT(30)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_PD             BIT(29)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_PD             BIT(28)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_PD              BIT(27)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_THM_PD               BIT(26)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_RST             BIT(25)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_RST             BIT(24)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_RST            BIT(23)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_RST            BIT(22)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_RST             BIT(21)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_THM_RSTN             BIT(20)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_ANALOG_PLL_RESERVED  BIT(19)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_REF_SEL         BIT(18)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_N               BIT(17)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_IBIAS           BIT(16)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_SDM_EN          BIT(15)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_MOD_EN          BIT(14)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_DIV_S           BIT(13)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_RESERVED        BIT(12)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_CLKOUT_EN       BIT(11)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_NINT            BIT(10)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_KINT            BIT(9)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_CCS_CTRL        BIT(8)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_IL_DIV2         BIT(7)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_OL_DIV2         BIT(6)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_TEST_EN         BIT(5)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_DPLL_BIST_EN         BIT(4)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_REF_SEL         BIT(3)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_N               BIT(2)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_IBIAS           BIT(1)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_SDM_EN          BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_REG_SEL_CFG_1 */

#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_MOD_EN          BIT(31)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_DIV_S           BIT(30)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_RESERVED        BIT(29)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_CLKOUT_EN       BIT(28)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_NINT            BIT(27)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_KINT            BIT(26)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_CCS_CTRL        BIT(25)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_IL_DIV2         BIT(24)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_OL_DIV2         BIT(23)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_TEST_EN         BIT(22)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_MPLL_BIST_EN         BIT(21)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_REF_SEL        BIT(20)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_N              BIT(19)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_IBIAS          BIT(18)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_SDM_EN         BIT(17)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_MOD_EN         BIT(16)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_DIV_S          BIT(15)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_RESERVED       BIT(14)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_CLKOUT_EN      BIT(13)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_DIV1_EN        BIT(12)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_DIV2_EN        BIT(11)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_DIV3_EN        BIT(10)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_DIV5_EN        BIT(9)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_DIV7_EN        BIT(8)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_NINT           BIT(7)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_KINT           BIT(6)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_CCS_CTRL       BIT(5)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_IL_DIV2        BIT(4)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_OL_DIV2        BIT(3)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_TEST_EN        BIT(2)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TWPLL_BIST_EN        BIT(1)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_REF_SEL        BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_REG_SEL_CFG_2 */

#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_N              BIT(31)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_IBIAS          BIT(30)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_SDM_EN         BIT(29)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_MOD_EN         BIT(28)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_DIV_S          BIT(27)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_RESERVED       BIT(26)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_CLKOUT_EN      BIT(25)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_DIV1_EN        BIT(24)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_DIV2_EN        BIT(23)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_DIV3_EN        BIT(22)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_DIV5_EN        BIT(21)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_DIV7_EN        BIT(20)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_NINT           BIT(19)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_KINT           BIT(18)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_CCS_CTRL       BIT(17)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_IL_DIV2        BIT(16)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_OL_DIV2        BIT(15)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_TEST_EN        BIT(14)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_CPPLL_BIST_EN        BIT(13)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_REF_SEL         BIT(12)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_N               BIT(11)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_IBIAS           BIT(10)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_SDM_EN          BIT(9)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_MOD_EN          BIT(8)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_DIV_S           BIT(7)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_RESERVED        BIT(6)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_CLKOUT_EN       BIT(5)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_NINT            BIT(4)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_KINT            BIT(3)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_CCS_CTRL        BIT(2)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_IL_DIV2         BIT(1)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_OL_DIV2         BIT(0)

/* REG_ANLG_PHY_G1_ANALOG_BB_TOP_REG_SEL_CFG_3 */

#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_TEST_EN         BIT(9)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_GPLL_BIST_EN         BIT(8)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_THM_RUN              BIT(7)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_THM_RESERVED         BIT(6)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_THM_BG_RBIAS_MODE    BIT(5)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_THM_TEST_SEL         BIT(4)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_THM_BP_MODE          BIT(3)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_THM_BP_DATA          BIT(2)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_ANA_BB_RESERVED      BIT(1)
#define BIT_ANLG_PHY_G1_DBG_SEL_ANALOG_BB_TOP_TEST_PLL_THM_MUX     BIT(0)


#endif /* ANLG_PHY_G1_H */

