#
# sprd_cpp.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#
KO_MODULE_NAME := sprd_cpp
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

CPP_DIR := $(BSP_BOARD_CAMERA_MODULE_CPP_VERSION)
KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/$(CPP_DIR)/*.c)

#
# Build Options
#
ccflags-y += -I$(KO_MODULE_PATH)/../common
ccflags-y += -I$(KO_MODULE_PATH)/../interface

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
