#
# sprdwl_ng.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

ifeq ($(filter $(strip $(BSP_BOARD_WLAN_DEVICE)),sc2332 sc2355),)
$(error no BSP_BOARD_WLAN_DEVICE, pls fix it !!!)
endif

WLAN_DEVICE := $(strip $(BSP_BOARD_WLAN_DEVICE))

#
# Source List
#
KO_MODULE_NAME := sprdwl_ng
KO_MODULE_PATH := $(src)/$(WLAN_DEVICE)
KO_MODULE_SRC  :=

KO_MODULE_SRC += \
	$(shell find $(KO_MODULE_PATH) -name "*.c")

#
# Build Options
#
ifeq ($(strip $(WLAN_DEVICE)),sc2332)
ccflags-y += -DDEBUG
else ifeq ($(strip $(WLAN_DEVICE)),sc2355)
ccflags-y += -DSC2355_FTR -DSC2355_TX_FILTER -DSC2355_QOS_MAP
ccflags-y += -DIBSS_SUPPORT -DIBSS_RSN_SUPPORT
ccflags-y += -DNAN_SUPPORT
ccflags-y += -DRTT_SUPPORT
ccflags-y += -DSC2355_RX_NO_LOOP
ccflags-y += -DACS_SUPPORT -DSC2355_HW_CSUM
ccflags-y += -DWMMAC_WFA_CERTIFICATION
ccflags-y += -DCOMPAT_SAMPILE_CODE
ccflags-y += -DRND_MAC_SUPPORT
ccflags-y += -DSOFTAP_HOOK
ccflags-y += -DATCMD_ASSERT
ccflags-y += -DTCPACK_DELAY_SUPPORT
  ifeq ($(strip $(BSP_BUILD_VARIANT)),userdebug)
  ccflags-y += -DCONFIG_SPRD_WCN_DEBUG
  endif
ccflags-y += -DSPLIT_STACK
endif

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
