obj-$(CONFIG_SPRD_SHARKLE_POWER_DEBUG)	+= sprd_sharle_pdbg.o
sprd_sharle_pdbg-objs := sprd_pdbg_core.o sprd_pdbg_sharkle.o

obj-$(CONFIG_SPRD_PIKE2_POWER_DEBUG)	+= sprd_pike2_pdbg.o
sprd_pike2_pdbg-objs := sprd_pdbg_core.o sprd_pdbg_pike2.o

obj-$(CONFIG_SPRD_SHARKL3_POWER_DEBUG)	+= sprd_sharl3_pdbg.o
sprd_sharl3_pdbg-objs := sprd_pdbg_core.o sprd_pdbg_sharkl3.o

obj-$(CONFIG_SPRD_SHARKL5_POWER_DEBUG)	+= sprd_sharl5_pdbg.o
sprd_sharl5_pdbg-objs := sprd_pdbg_core.o sprd_pdbg_sharkl5.o

obj-$(CONFIG_SPRD_SHARKL5PRO_POWER_DEBUG)	+= sprd_sharl5pro_pdbg.o
sprd_sharl5pro_pdbg-objs := sprd_pdbg_core.o sprd_pdbg_sharkl5pro.o

obj-$(CONFIG_SPRD_ROC1_POWER_DEBUG)	+= sprd_roc1_pdbg.o
sprd_roc1_pdbg-objs := sprd_pdbg_core.o sprd_pdbg_roc1.o

obj-$(CONFIG_SPRD_ORCA_POWER_DEBUG)	+= sprd_orca_pdbg.o
sprd_orca_pdbg-objs := sprd_pdbg_core.o sprd_pdbg_orca.o
